config/routes.rb
Rails.application.routes.draw do
  get 'home/lists'
  get 'home/index'

  devise_for :users
  resources :users, only: [:update, :show]
  resources :items
  root to: 'home#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  def days_left
   7 - (DateTime.now.to_date - created_at.to_date).to_i
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def admin?
    role == 'admin'
  end
  def moderator?
    role == 'moderator'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
  
    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def lists
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
      @item = Item.new(params.require(:item).permit(:name))
      @item.user = current_user
      @item.save
      redirect_to :back
      authorize @item
  end


  def destroy
    item = Item.find(params[:id])

    item.destroy

    redirect_to :back
  end
end

# def days_left
#    7 - (DateTime.now.to_date - created_at.to_date).to_i
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  def show
    @user = User.find(params[:id])
  end


     def update
       if current_user.update_attributes(user_params)
         flash[:notice] = "User information updated"
         redirect_to edit_user_registration_path
       else
         flash[:error] = "Invalid user information"
         redirect_to edit_user_registration_path
       end
     end

     private

     def user_params
       params.require(:user).permit(:name,:email_favorites)
     end
   end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<br>
<div class="jumbotron" align="center">
  <h1>Welcome to Mark-It-Off</h1>
   <p>The task manager that allows you to focus on the task and not the manager.</p>
  <h4>
 <%= link_to "Sign In", new_user_session_path, class: 'btn btn-success' %> or
 <%= link_to "Get Started", new_user_registration_path, class: 'btn btn-success' %> today!
 </h4>
</div>


<div class="row">
  <div class="col-md-4" align="center">
    <h1> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></h1>
      <h3> Check stuff off. </h3>
  </div>
    <div class="col-md-4" align="center">
      <h1> <span class="glyphicon glyphicon-time" aria-hidden="true"></span></h1>
        <h3> Get Clocks. </h3>
    </div>
    <div class="col-md-4" align="center">
      <h1> <span class="glyphicon glyphicon-tree-conifer" aria-hidden="true"></span></h1>
        <h3> Grow a tree. </h3>
    </div>
  </div>

app/views/home/lists.html.erb
<ul>
  <% current_user.items.each do |item| %>
    <li><%= item.name %>
      <%= item.days_left %>
      <%= link_to "", item, method: :delete, class: 'glyphicon glyphicon-ok' %>
    </li>

  <% end %>
</ul>



<%= form_for Item.new do |f| %>

  Name: <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Markitoff</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
    <li><%= link_to "Home", home_index_path %></li>
    <div class="pull-right user-info">
      <% if current_user %>
        Hello <%= current_user.email %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </div>
  </ul>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <%= yield %>
  </div>
</body>
</html>

app/views/users/_user.html.erb
<div class='info'>
  <h2 class="info-name">
    <%= @user.name %>
  </h2>

  <h4 class='info-email'>
    <%= @user.email %>
  </h4>
</br>

app/views/users/show.html.erb
<%= render @user %>